### ISSUE TITLE
A problem about running the code

### ISSUE THREAD

**Issue by fsdundar** [met4citizen/Hypergraph#3]
Dear developers,

thank you for the amazing work. I cloned the repo and run on localhost. The html file is opened, however I can neither specify a rule or run a time evolution for the hypergraph. I think I might have ommitted some obvious step. Could you kindly guide me as regards the problem?

Best wishes,
Furkan Semih.

**Comment by met4citizen** [comment]
Hi,

I tried replicating the issue but was unable to reproduce it. If the web app works [here](https://met4citizen.github.io/Hypergraph/), the problem is most likely related to your server-side setup.

Could you let me know what web server you are using? Please note that the app needs to be served via a web server — opening the files directly from your file system won't work due to browser security policies.

Also, could you check the browser console for any error messages? In Chrome, you can open the console with the keyboard shortcut `Ctrl+Shift+J` (Win/Linux) or `Command+Option+J` (Mac). The console log might provide helpful clues about what's going wrong.

**Comment by fsdundar** [comment]
Hi,

thanks for the quick reply. I get the following error on Chrome console:

> Failed to load module script: Expected a JavaScript module Simulator.mjs script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

I am using nginx on MacOS Sonoma 14.6.1

**Comment by met4citizen** [comment]
OK, that explains it. Your web server doesn't know how to serve JavaScript module files (.mjs). I don't use nginx myself, but somewhere in your nginx configuration, there should be a `mime.types` configuration file. You need to update the existing entry from `application/javascript js;` to `application/javascript js mjs;`. That should fix it.

**Comment by fsdundar** [comment]
I solved the issue by using Docker and modifying the file you mentioned. Though I could still not managed to resolve the issue on bare MacOS.

Thanks for you help.
